function eta = BijBji_contraction( smoothModRSanisotropyBijTerm )

eta =  sum( smoothModRSanisotropyBijTerm(:,[1,5,9]).^2 , 2 ) + ...
        2*  smoothModRSanisotropyBijTerm(:,2) .* smoothModRSanisotropyBijTerm(:,4) + ...
        2*  smoothModRSanisotropyBijTerm(:,3) .* smoothModRSanisotropyBijTerm(:,7) + ...
        2*  smoothModRSanisotropyBijTerm(:,6) .* smoothModRSanisotropyBijTerm(:,8) ;