function d2TijdXidXj = d2TijdXidXj_v100b1( Tij_all , D_operator2D_all , D2_operator2D_all )

d2TijdXidXj =   [   D2_operator2D_all{1} * Tij_all(:,1) , ...
                    D_operator2D_all{1}  * D_operator2D_all{2} * Tij_all(:,2) , ...
                    D_operator2D_all{1}  * D_operator2D_all{3} * Tij_all(:,3) , ...
                    D_operator2D_all{2}  * D_operator2D_all{1} * Tij_all(:,4) , ...
                    D2_operator2D_all{1} * Tij_all(:,5) , ...
                    D_operator2D_all{2}  * D_operator2D_all{3} * Tij_all(:,6) , ...
                    D_operator2D_all{3}  * D_operator2D_all{1} * Tij_all(:,7) , ...
                    D_operator2D_all{3}  * D_operator2D_all{2} * Tij_all(:,8) , ...
                    D2_operator2D_all{3} * Tij_all(:,9) ...
                ] ;