function [ Vars_TMean , RS_TMean ] = importCSV_MeanFields_v010(filename,iXYZ)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [U0,U1,U2,UMEAN0,UMEAN1,UMEAN2,UPRIME2MEAN0,UPRIME2MEAN1,UPRIME2MEAN2,UPRIME2MEAN3,UPRIME2MEAN4,UPRIME2MEAN5,NUSGS,P,PMEAN,CELLTYPE]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [U0,U1,U2,UMEAN0,UMEAN1,UMEAN2,UPRIME2MEAN0,UPRIME2MEAN1,UPRIME2MEAN2,UPRIME2MEAN3,UPRIME2MEAN4,UPRIME2MEAN5,NUSGS,P,PMEAN,CELLTYPE]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [U0,U1,U2,UMean0,UMean1,UMean2,UPrime2Mean0,UPrime2Mean1,UPrime2Mean2,UPrime2Mean3,UPrime2Mean4,UPrime2Mean5,nuSgs,p,pMean,CellType] = importfile('pp.csv',2, 100);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/01/28 13:57:53

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%%
dataArray = [ dataArray{1:end-1} ] ;

%% Allocate imported array to column variable names
% U0 = dataArray{:, 1};
% U1 = dataArray{:, 2};
% U2 = dataArray{:, 3};
% UMean0 = dataArray{:, 4};
% UMean1 = dataArray{:, 5};
% UMean2 = dataArray{:, 6};
% UPrime2Mean0 = dataArray{:, 7};
% UPrime2Mean1 = dataArray{:, 8};
% UPrime2Mean2 = dataArray{:, 9};
% UPrime2Mean3 = dataArray{:, 10};
% UPrime2Mean4 = dataArray{:, 11};
% UPrime2Mean5 = dataArray{:, 12};
% nuSgs = dataArray{:, 13};
% p = dataArray{:, 14};
% pMean = dataArray{:, 15};
% CellType = dataArray{:, 16};

% Vars        = dataArray{:,[1:3,14,13]} ; 
Vars_TMean  = dataArray(iXYZ , [4:6,15,13]) ;
RS_TMean    = dataArray(iXYZ , 7:12 );



