%% script for reading cell center values from csv file generated by paraView
%% tested with one snapshot containing xyz, and one without. velocity, pressure, nuSgs values matched completely (exactly 0 difference)

function [ Vars , XYZ , iXYZ ] = importCSV_ParaView_UPNUsnapshots_wXYZ_cellCenter_v110b3(filename,iXYZ)

%% 
if nargin<2
    iXYZ = [] ;
end

%% Initialize variables.
delimiter = ',';
startRow = 2;
endRow = inf;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%	column11: double (%f)
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Create output variable)
testCaseLES04fcellCenter20 = [dataArray{1:end-1}];

%% droping column containing NaNs (resulting from less number of columns than 10 which is default)
NpointsExported = length(testCaseLES04fcellCenter20) ;
numNans = sum( isnan( testCaseLES04fcellCenter20) ,1 ) ;

testCaseLES04fcellCenter20( : , numNans > .1*NpointsExported ) = [];

%%
if ~isempty(iXYZ) && ( max(iXYZ) > NpointsExported )
    Vars    = [];
    warning('the entered index does not match the snapshot! could be a result of inclomplete export by paraView. returning empty for all variable!')
    return
end

%% conditional statement to work for snapshots with all PROPER snapshots.
%% with or without XYZ data
%% with or without k data
%% with or without nuSgs
if size( testCaseLES04fcellCenter20,2 ) == 10 
    if isempty(iXYZ)
        [ XYZ , iXYZ , ~ ] = unique(testCaseLES04fcellCenter20(:,5:7) , 'rows' , 'stable') ;
    else
        XYZ = testCaseLES04fcellCenter20(:,5:7) ;
        disp('did not recompute xyz data, although there is data available.')
    end
    
    Vars    = testCaseLES04fcellCenter20(iXYZ,[1:3,9,8]) ;
    
    
    
%%
elseif size( testCaseLES04fcellCenter20,2 ) == 12 
    
    disp('snapshot supposedly contains k data. if not terminate.')
    
    if isempty(iXYZ)
        [ XYZ , iXYZ , ~ ] = unique(testCaseLES04fcellCenter20(:,5:7) , 'rows' , 'stable') ;
    else
        XYZ = testCaseLES04fcellCenter20(:,5:7) ;
        disp('did not recompute xyz data, although there is data available.')
    end
    
    Vars    = testCaseLES04fcellCenter20(iXYZ,[1:3,11,10]) ;
   
elseif size( testCaseLES04fcellCenter20,2 ) == 11 
    
    disp('snapshot supposedly contains k data. if not terminate.')
    
    if isempty(iXYZ)
        [ XYZ , iXYZ , ~ ] = unique(testCaseLES04fcellCenter20(:,5:7) , 'rows' , 'stable') ;
    else
        XYZ = testCaseLES04fcellCenter20(:,5:7) ;
        disp('did not recompute xyz data, although there is data available.')
    end
    
    Vars    = testCaseLES04fcellCenter20(iXYZ,[1:3,10,9]) ;
   
    
    
%%
elseif size( testCaseLES04fcellCenter20,2 ) == 6 
    Vars    = testCaseLES04fcellCenter20(iXYZ,[1:3,5,4]) ;
    XYZ     = [];
    disp('no xyz data.')
    
    
    
    
%%
elseif size( testCaseLES04fcellCenter20,2 ) == 7
    Vars    = testCaseLES04fcellCenter20(iXYZ,[1:3,6,5]) ;
    XYZ     = [];
    disp('no xyz data. snapshot supposedly contains k data.')
    
    
    
%%
elseif size( testCaseLES04fcellCenter20,2 ) == 5
    Vars    = [ testCaseLES04fcellCenter20(iXYZ,1:4) , zeros(length(iXYZ),1) ] ;
    XYZ     = [];
    disp('no xyz data. no nuSgs data. returning zero for nuSgs...')
    
    
    
    
%%
else
    Vars    = [];
    warning('flawed snapshot! returning empty!')
    return
end
