

function [ output_RANS , output_newRANS , output_smoothRANS , output_smoothUiUj , ...
    output_RS , output_modRS , output_newModRS , output_smoothModRS_linear , output_smoothModRS_natural , ...
    output_POIS , output_CONT , ...
    X,Y,XY , smoothX,smoothY,smoothXY , newX,newY,newXY] = ...
    OF_BFS_sourceTerms_v362b1( fileName )

%%
addpath('/Users/siavashtoosi/Documents/MATLAB/OpenFOAM/MainRequiredScripts_v900','-end')
addpath('~/supportingScripts_MATLAB')

%%
load(fileName)

%%
fileName_fineGrid = [ fileName(1:end-4) , '_2timesFinerGrid_v001.mat' ] ;
make2timesFiner_v001( X_up,Y_up , X_down,Y_down , fileName_fineGrid ) ;

%%
X   = { X_up , X_down };
Y   = { Y_up , Y_down };
XY  = { XY_averagable_all };

%%
if strcmpi(which_flow,'BFS')
    smoothGridFileName = 'smoothedFineGrid_BFSv312setup_v110.mat' ;
elseif strcmpi(which_flow,'channel')
    smoothGridFileName = 'smoothedFineGrid_channelRe590moser_v120.mat' ;
end

load( smoothGridFileName  , 'smoothXYcloud_tot','smoothX_*' , 'smoothY_*' )

smoothX   = { smoothX_up , smoothX_down };
smoothY   = { smoothY_up , smoothY_down };
smoothXY  = { smoothXYcloud_tot };

%%
load( fileName_fineGrid  , 'newXYcloud_tot','newX_*' , 'newY_*' )

newX   = { newX_up , newX_down };
newY   = { newY_up , newY_down };
newXY  = { newXYcloud_tot };

%%
gradOperator2D_all      = [ Dx_operator2D_all   ; Dy_operator2D_all     ; Dz_operator2D_all ];
D_operator2D_all        = { Dx_operator2D_all   , Dy_operator2D_all     , Dz_operator2D_all };
D2_operator2D_all       = { D2x_operator2D_all  , D2y_operator2D_all    , D2z_operator2D_all };

%% reconstruct 9 components tensors for simplicity
Rij_wholeDomain_ZTMean_Vec          = RS_wholeDomain_ZTMean_Vec(:,[1,4,5,4,2,6,5,6,3]);
modRij_wholeDomain_ZTMean_Vec       = modRS_wholeDomain_ZTMean_Vec(:,[1,4,5,4,2,6,5,6,3]);
epsilonij_wholeDomain_ZTMean_Vec    = epsilon_wholeDomain_ZTMean_Vec(:,[1,4,5,4,2,6,5,6,3]);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% mean momentum equation
[ output_RANS , output_newRANS , output_smoothRANS , output_smoothUiUj ] = ...
    budgets_meanMomentum_singleGrid_v211b1( ...
    Vars_wholeDomain_ZTMean_Vec , modVars_wholeDomain_ZTMean_Vec , ...
    Rij_wholeDomain_ZTMean_Vec , modRij_wholeDomain_ZTMean_Vec , ...
    divUiUj_wholeDomain_ZTMean_Vec , UkDUiDxK_wholeDomain_ZTMean_Vec , skewSymmetric_wholeDomain_ZTMean_Vec , ...
    gradU_wholeDomain_ZTMean_Vec , gradP_wholeDomain_ZTMean_Vec , laplacianUi_wholeDomain_ZTMean_Vec , ...
    divTauSgs_wholeDomain_ZTMean_Vec ,...
    tauKKsgs_wholeDomain_ZTMean_Vec , ...
    divOperator2D_all ,...
    XY_averagable_all , X_up,Y_up , X_down,Y_down , ...
    fluid_rho , fluid_nu , BL_tauWall , ...
    which_flow , smoothGridFileName , fileName_fineGrid ) ;

%% continuity equation
output_CONT = budgets_continuity_singleGrid_v100b1( ...
    divU_wholeDomain_ZTMean_Vec , absDivU_wholeDomain_ZTMean_Vec , ...
    XY_averagable_all , X_up,Y_up , X_down,Y_down ) ;

%% Poinsson eqation
output_POIS = budgets_meanPoisson_singleGrid_v100b1( ...
    Vars_wholeDomain_ZTMean_Vec , Rij_wholeDomain_ZTMean_Vec , tauSgs_wholeDomain_ZTMean_Vec , ...
    skewSymmetric_wholeDomain_ZTMean_Vec , gradU_wholeDomain_ZTMean_Vec , divTauSgs_wholeDomain_ZTMean_Vec , ...
    D_operator2D_all , D2_operator2D_all , ...
    divOperator2D_all , laplacianOperator2D_all , ...
    XY_averagable_all , X_up,Y_up , X_down,Y_down , ...
    fluid_rho ) ;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[ output_RS , output_modRS , output_newModRS , output_smoothModRS_linear , output_smoothModRS_natural ] = ...
budgets_meanRS_singleGrid_v321b1( ...
    Vars_wholeDomain_ZTMean_Vec , ...
    modVars_wholeDomain_ZTMean_Vec , ...
    Rij_wholeDomain_ZTMean_Vec , ...
    modRij_wholeDomain_ZTMean_Vec , ...
    UiUjUk_wholeDomain_ZTMean_Vec , ...
    epsilonij_wholeDomain_ZTMean_Vec , ...
    UiP_wholeDomain_ZTMean_Vec , ...
    PgradU_wholeDomain_ZTMean_Vec , ...
    UiDtauJKdxK_wholeDomain_ZTMean_Vec , ...
    UiDmodTauJKdxK_wholeDomain_ZTMean_Vec , ...
    TikDujDxk_wholeDomain_ZTMean_Vec , ...
    dUjTikDxk_wholeDomain_ZTMean_Vec , ...
    dUjmodTikDxk_wholeDomain_ZTMean_Vec , ...
    RSeq_altConvProdTurbTrans_wholeDomain_ZTMean_Vec , ...
    RSeq_allPressure_wholeDomain_ZTMean_Vec , ...
    modRSeq_allPressure_wholeDomain_ZTMean_Vec , ...
    RSeq_allViscous_wholeDomain_ZTMean_Vec , ...
    Sij_wholeDomain_ZTMean_Vec , ...
    D_operator2D_all , D2_operator2D_all , ...
    divOperator2D_all , gradOperator2D_all, laplacianOperator2D_all , ...
    XY_averagable_all , X_up,Y_up , X_down,Y_down , ...
    fluid_rho , fluid_nu , smoothGridFileName , fileName_fineGrid ) ;